Exercise on Functions:

Task - 1:

In [ ]:
def convert_l(value, from_unit):
  if from_unit == 'm':
    return value * 3.28084
  elif from_unit == 'ft':
    return value / 3.28084
  else:
      raise ValueError("Unsupported lenth unit.")

def convert_w(value, from_unit):
    if from_unit == 'kg':
      return value * 2.20462
    elif from_unit == 'lbs':
      return value / 2.20462
    else:
        raise ValueError("Unsupported weight unit.")

def convert_v(value, from_unit):
  if from_unit == 'l':
    return value * 0.264172
  elif from_unit == 'gal':
    return value / 0.264172
  else:
    raise ValueError("Unsupported volume unit.")

def main():
  print("unit converter")
  print("1. length")
  print("2. weight")
  print("3. volume")
  try:
    choice = int(input("Choose conversion type (1-3):"))
    if choice == 1:
      value = float(input("enter the value of length:"))
      unit = input("enter the unit (m/ft):").strip().lower()
      convert = convert_l(value, unit)
      print(f"converted value:{converted:2f}")
    elif choice == 2:
        value = float (input("enter the value of weight:"))
        unit = input("enter the unit (kg/lbs):").strip().lower()
        convert = convert_w(value, unit)
        print(f"converted value:{converted:2f}")
    elif choice == 3:
          value = float (input("enter the value of volume:"))
          unit = input("enter the unit(l/gal):").strip().lower()
          converted = convert_v(value, unit)
          print(f"converted value:{converted:2f}")
    else:
      print("invalid choice.")
  except ValueError as e:
     print(f"Error:{e}.")
     if __name__ == "__main__":
         main()



Task - 2:

In [ ]:
def get_numbers():
  while True:
      try:
        return[float(num) for num in input ("enter numbers separated by spaces:").split() ]
      except ValueError:
        print("invalid input.")
def main():
   print("choose an operater:")
   print("1. sum")
   print("2. Average")
   print("3. Maximum")
   print("4. Minimum")
   choice = input("enter choice (1-4):")
   numbers = get_numbers()
   if choice == '1':
    print("sum:", sum(numbers))
   elif choice  == '2':
    print("Average:", sum(numbers)/len(numbers))
   elif choice == '3':
    print("Maximum:", max(numbers))
   elif choice == '4':
    print("Minimum:" , min(numbers))
   else:
    print("invalid choice.")
if __name__ == "__main__":
    main()


choose an operater:
1. sum
2. Average
3. Maximum
4. Minimum
enter choice (1-4):4
enter numbers separated by spaces:4 7 9 
Minimum: 4.0


Exercise on List Manipulation:

1. Extract Every Other Element:

In [ ]:
def extract_every_other(lst):
  return lst[::2]
  lst = [1,2,3,4,5,6]
  output_list = extract_every_other(lst)
  print(output_list)

Slice a Sublist:

In [ ]:
def get_sublist(lst, start, end):
  return lst[start:end+1]
  lst =[1,2,3,4,5,6]
  start = 1
  end = 5
  output_list = get_sublist(lst, start, end)
  print(output_sublist)

Reverse a List Using Slicing:

In [ ]:
def reverse_list(lst):
  return lst[::-1]
  input_list = [1,2,3,4,5]
  reversed_list = reverse_list(input_list)
  print(reversed_list)

Remove the First and Last Elements:

In [ ]:
def remove_first_last(lst):
  return lst[1:-1]
  input_lst = [1,2,3,4,5]
  resulting_sublist = remove_first_last(input_list)
  print(resulting_sublist)

Get the First n Elements:

In [ ]:
def get_first_n(lst, n):
  return lst[:n]
  input_list = [1,2,3,4,5]
  n = 3
  first_n_elements = get_first_n(input_list, n)
  print(first_n_elements)

Extract Elements from the End:

In [ ]:
def get_last_n(lst, n):
  return lst[-n:]
  input_list =[1,2,3,4,5]
  n = 2
  last_n_elements = get_last_n(input_list, n)
  print(last_n_elements)

Extract Elements in Reverse Order:

In [ ]:
def reverse_skip(lst):
  return lst[-2::-2]
  input_list = [1,2,3,4,5,6]
  result = reverse_skip(input_list)
  print(result)

Exercise on Nested List:

Flatten a Nested List:

In [ ]:
def flatten(lst):
  flatten_list = []
  for sublist in lst:
    for item in sublist:
      flatten_list.append(item)
      return flatten_list
      nested_list = [[1,2], [3,4],[5]]
      flattened = flatten(nested_list)
      print(flattened)

Accessing Nested List Elements:

In [ ]:
def access_nested_element(lst, indices):
  element = lst
  for index in indices:
    element = element[index]
    return element
    lst = [[1,2,3],[4,5,6],[7,8,9]]
    indices = [1,2]
    result = access_nested_element(lst, indices)
    print(result)

Sum of All Elements in a Nested List:

In [ ]:
def sum_nested(lst):
  total = 0
  for items in lst:
    if isinstance(items, list):
      total += sum_nested(item)
    else:
      total += item
      return total
      nested_list = [[1,2],[3,4],[4,5], 6]
      result = sum_nested(nested_list)
      print(result)

Remove Specific Element from a Nested List:

In [ ]:
def remove_element(lst, elem):
  for i in range(len(lst)):
    if isinstance(lst[i], list):
      lst [i] = remove_element(lst[i], elem)
    else:
      while elem in lst [i]:
        lst[i].remove(elem)
    return lst
    nested_list = [[1,2],[3,2],[4,5]]
    elem = 2
    result = remove_element(nested_list, elem)
    print(result)

Find the Maximum Element in a Nested List:

In [ ]:
def find_max(lst):
  max_element = float('-inf')
  for item in lst:
    if isinstance(item, list):
      max_element = max (max_element, find_max(item))
    else:
      max_element = max(max_element, item)
    return max_element
    nested_list = [[1,2],[3,[4,5],6]]
    result = find_max(nested_list)
    print(result)

Count Occurrences of an Element in a Nested List:

In [ ]:
def count_occurrences(lst, elem):
  count = 0
  for items in lst:
    if isinstance(item, list):
      count += count_occurrences(item, elem)
    else:
      count += item == elem
    return count
    nested_list = [[1,2],[2,3],[2,4]]
    elem = 2
    result = count_occurrences(nested_list, elem)
    print(result)

Flatten a List of Lists of Lists:

In [ ]:
def deep_flatten(lst):
  flattened_list = []
  for item in lst:
    if isinstance(item, list):
      flattened_list.extend(deep_flatten(item))
    else:
      flattened_list.append(item)
    return flattened_list
    nested_list = [[[1,2],[3,4],[5,6],[6,7]]]
    result = deep_flatten(nested_list)
    print(result)

Nested List Average:

In [ ]:
def average_nested(lst):
  total = 0
  count = 0
  def flatten(lst):
    nonlocal total, count
    for item in lst:
      if isinstance(item, list):
        flatten(item)
      else:
        total += item
        count += 1
    flatten(lst)
  nested_list = [[1,2],[3,4],[5,6]]
  result = average_nested(nested_list)
  print(result)

Numpy

In [ ]:
import numpy as np

arr_1d = np.array([6, 7, 8 , 9 ,10])
arr_2d = np. array ([[6,7,8], [9, 10, 11]])
arr_zero = np.zeros((6,7))
arr_ones = np.ones((7,6))
arr_random = np.random.rand(7,7)

print("1D Array:", arr_1d)
print("2D Array:",arr_2d)
print ("Zero Array:",arr_zero)
print ("ones Array:", arr_ones)
print ("random Array:", arr_random)

reshape_arr = arr_1d.reshape(5,1)
print("Reshaped 1D Array:", reshape_arr)


print("Element at (0,1):", arr_2d[0,1])
print("first row:", arr_2d[0])
print("Last column:", arr_2d[:,-1])

1D Array: [ 6  7  8  9 10]
2D Array: [[ 6  7  8]
 [ 9 10 11]]
Zero Array: [[0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]
ones Array: [[1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]]
random Array: [[0.56344251 0.70456973 0.58736269 0.3894193  0.96015638 0.12820117
  0.75471235]
 [0.85522952 0.09305274 0.85851747 0.27012992 0.77383268 0.51237163
  0.61095011]
 [0.88378686 0.20667244 0.56229253 0.70613531 0.69300281 0.35696129
  0.15805604]
 [0.38677209 0.67047126 0.47162918 0.72656999 0.33031948 0.47016884
  0.41221705]
 [0.70239629 0.61042079 0.93167747 0.77775342 0.90437421 0.67846392
  0.85843267]
 [0.96811927 0.6323935  0.94699708 0.09136014 0.26109145 0.51856244
  0.16275096]
 [0.3998657  0.11326558 0.9707969  0.19307663 0.53893839 0.15412524
  0.39455299]]
Reshaped 1D Array: [[ 6]
 [ 7]
 

In [ ]:
a = np.array([1,2,3,4,5])
b = np.array([6,7,8,9,10])

print("Addition:", a + b)
print("subtraction:", a - b)
print("Multiplication:", a * b)
print("Division:", a / b)

print("Exponential:", np.exp(a))
print("square root :", np.sqrt(a))
print("Logarithm:", np.log(a))

matrix_A = np.array([[4,5],[6,7]])
matrix_B = np.array([[8,9],[10,11]])

print("DOt Product:", np.dot(matrix_A, matrix_B))
print("Inverse of A:", np.linalg.inv(matrix_A))
print("Determinant of A:", np.linalg.det(matrix_A))

Addition: [ 7  9 11 13 15]
subtraction: [-5 -5 -5 -5 -5]
Multiplication: [ 6 14 24 36 50]
Division: [0.16666667 0.28571429 0.375      0.44444444 0.5       ]
Exponential: [  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591 ]
square root : [1.         1.41421356 1.73205081 2.         2.23606798]
Logarithm: [0.         0.69314718 1.09861229 1.38629436 1.60943791]
DOt Product: [[ 82  91]
 [118 131]]
Inverse of A: [[-3.5  2.5]
 [ 3.  -2. ]]
Determinant of A: -2.000000000000003


In [ ]:

arr = np.array([40,50,60,70,80,])
print("First three elements:", arr[:3])
print("last two elements:", arr[-2:])
print("Every other elements:", arr[::2])


arr_2d = np.array([[3,4,5],[6,7,8],[9,10,11]])
print ("First two rows:", arr_2d[:2, :])
print ("Last column:", arr_2d[:, -1])


First three elements: [40 50 60]
last two elements: [70 80]
Every other elements: [40 60 80]
First two rows: [[3 4 5]
 [6 7 8]]
Last column: [ 5  8 11]


In [ ]:
A = np.array([[4],[5],[6]])
B = np.array([30 , 40 ,50])

c = A + B
print("Broadcasting result:",c)

Broadcasting result: [[34 44 54]
 [35 45 55]
 [36 46 56]]


In [ ]:
arr = np.array([3,4,5])
try:
  print(arr[5])
except IndexError as e:
  print("IndexError:", e)

try:
  a = np.array([3,4,5])
  b = np.array([[6,7],[8,9]])
  print(a + b)
except ValueError as e:
  print("ValueError:", e)

IndexError: index 5 is out of bounds for axis 0 with size 3
ValueError: operands could not be broadcast together with shapes (3,) (2,2) 


Experiment: How Fast is Numpy?

In [ ]:
import numpy as np
import time

# List size
size = 1_000_000

# Generate random lists and NumPy arrays
a_list = list(range(size))
b_list = list(range(size))

a_np = np.arange(size)
b_np = np.arange(size)

# Element-wise Addition
start = time.time()
c_list = [a + b for a, b in zip(a_list, b_list)]
end = time.time()
print(f"Python List Addition Time: {end - start:.5f} seconds")

start = time.time()
c_np = a_np + b_np
end = time.time()
print(f"NumPy Array Addition Time: {end - start:.5f} seconds")

# Element-wise Multiplication
start = time.time()
d_list = [a * b for a, b in zip(a_list, b_list)]
end = time.time()
print(f"Python List Multiplication Time: {end - start:.5f} seconds")

start = time.time()
d_np = a_np * b_np
end = time.time()
print(f"NumPy Array Multiplication Time: {end - start:.5f} seconds")

# Dot Product
start = time.time()
dot_list = sum(a * b for a, b in zip(a_list, b_list))
end = time.time()
print(f"Python List Dot Product Time: {end - start:.5f} seconds")

start = time.time()
dot_np = np.dot(a_np, b_np)
end = time.time()
print(f"NumPy Array Dot Product Time: {end - start:.5f} seconds")

# Matrix Multiplication
matrix_size = 1000
A_list = [[1] * matrix_size for _ in range(matrix_size)]
B_list = [[1] * matrix_size for _ in range(matrix_size)]

start = time.time()
C_list = [[sum(A_list[i][k] * B_list[k][j] for k in range(matrix_size)) for j in range(matrix_size)] for i in range(matrix_size)]
end = time.time()
print(f"Python List Matrix Multiplication Time: {end - start:.5f} seconds")

A_np = np.ones((matrix_size, matrix_size))
B_np = np.ones((matrix_size, matrix_size))

start = time.time()
C_np = np.dot(A_np, B_np)
end = time.time()
print(f"NumPy Array Matrix Multiplication Time: {end - start:.5f} seconds")


Python List Addition Time: 0.12147 seconds
NumPy Array Addition Time: 0.01433 seconds
Python List Multiplication Time: 0.11618 seconds
NumPy Array Multiplication Time: 0.01344 seconds
Python List Dot Product Time: 0.08041 seconds
NumPy Array Dot Product Time: 0.00369 seconds
